### PR TITLE
Added ~ separator

### PR DESCRIPTION
**Pull request by DaliborTrampota**
Added ~ separator one example --> https://www.youtube.com/watch?v=vyrFeUsO59E

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
thank you! could you add a test case for this in `test/separators.js`? It should pretty much look just like this one:
https://github.com/goto-bus-stop/get-artist-title/blob/7d3d19af4f0ad53d2cdb2f492ae90aa823010ed2/test/separators.js#L19-L21

**Comment by DaliborTrampota** [comment]
I also added so it removes (audio) from title. I hope it's no problem. I know it's all specific to one song (https://www.youtube.com/watch?v=vyrFeUsO59E) but I believe there's more songs with (audio) or have ~ separator in name. I'm also not very good with github pull requests so I hope I've done everything correctly.

**Comment by DaliborTrampota** [comment]
Also can you tell me what this means? I see red cross next to the commit. https://github.com/goto-bus-stop/get-artist-title/pull/34/commits/7395d8995c002176ca7bd76ed470c50a40cf4fab

**Comment by goto-bus-stop** [comment]
The tests were failing on that commit, but you fixed it in the next one, so it's all good now :)

**Review by goto-bus-stop — APPROVED** [review]
looks good to me 👍🏻  i'm at work now but i can prob release this in the evening.

**Comment by DaliborTrampota** [comment]
Perfect! And how does it work? Will I just do npm update and it will be with these changes?

**Comment by goto-bus-stop** [comment]
yep, you should get 1.3.1 when you do npm update ☺️

**Comment by DaliborTrampota** [comment]
Amazing thank you for the cooperation. Great job!

**Pull request merged**
